#
# Copyright (C) Grzegorz Skorupa 2018.
# Distributed under the MIT License (license terms are at http://opensource.org/licenses/MIT).
#
# This is Dockerfile template for Cricket based services
# 
# The file is used by Ant build to cereate Dockerfile.
# {{version}} parameter will be replaced automatically with the actual project version configured in build.xml
#
FROM java:8

VOLUME /dbdata

COPY dist/signomix-{{version}}.jar /usr/signomix/
COPY dist/config/cricket.json /usr/signomix/config/
COPY www /usr/signomix/www

WORKDIR /usr/signomix
RUN mkdir /usr/signomix/data
COPY dist/data/cricket_publickeystore.jks /usr/signomix/data


CMD ["java", "-Xms50m",  "-Xmx100m", "-jar", "./signomix-{{version}}.jar", "-r", "-c", "config/cricket.json"]